### ISSUE TITLE
Updating existing tree

### ISSUE THREAD

**Issue by DamjanZ** [lazychaser/laravel-nestedset#50]
Hi @lazychaser, I am currently using this package and so far I like it. But I got stuck in one part that probably is possible to do but I haven't found solution in documentation. :smile:

Can I use "create" method to update or delete all nodes which are not present in scope?

I need some method that'll do same job as [seeding/mass assingment](https://github.com/etrepat/baum#seedingmass-assignment) methods in [etrepat/baum](https://github.com/etrepat/baum) project.

In my example, I am trying to make forum where user can reorder the display of forum and subforum categories.

Thank you :smile:

**Comment by elieandraos** [comment]
i was wondering the same, how to update the order of existing tree nodes. the baum package has a mass assign by just passing an array of ids

**Comment by lazychaser** [comment]
The order is updated by inserting nodes before/after other node. You can also use `up` and `down` methods to move nodes around. But actually you can use your own ordering method (i.e. numeric value), this will not affect the tree.

**Comment by DamjanZ** [comment]
So basically, method `create` will rearrange whole table if I put same values but in different order? Or I should make my ordering method that'll do the job?

**Comment by elieandraos** [comment]
No, create will duplicate the table. you have to do the ordering logic. I am working on this right now, if i came up with something soon, I will share it.
It should be a static method on the model something like Model::rebuildTree($array)

**Comment by DamjanZ** [comment]
Ok, thanks for help!

**Comment by elieandraos** [comment]
@DamjanZ i made it work., i hope this can help you. 

First, for you to understand, i am working on a nested set ui, so basically do everything by dragging/dropping and sorting as in the image below: 

![tree]
(https://lh3.googleusercontent.com/DVcZOe7BrbmO8FF1Idl-wmp6VUSuzAnRLEqql3akF5Qn84eBKZefFosFZMOCEJ5JjDBHxVySmwlK59E=w2560-h1210-rw)

when i sort, i receive a full array in my post request, with the same hierarchy as the mass seeing but an id instead of title (this is generated by the drag/drop scripts basically), the array is something like that 

```
array:1 [
  0 => array:2 [
    "id" => 1
    "children" => array:3 [
      0 => array:2 [
        "id" => 4
        "children" => array:3 [
          0 => array:2 [
            "id" => 7
            "children" => []
          ]
          1 => array:2 [
            "id" => 5
            "children" => []
          ]
          2 => array:2 [
            "id" => 6
            "children" => []
          ]
        ]
      ]
      1 => array:2 [
        "id" => 3
        "children" => []
      ]
      2 => array:2 [
        "id" => 2
        "children" => []
      ]
    ]
  ]
]
```

The category ids are the good order, and also if a descendant has a new parent, and i just need to save them. I had to create 2 static methods in my model and call them form my controller method, one to first save new roots and another one to save descendants and their order.

```
	/**
	 * Resets all the nodes as roots
	 * @param type $categories 
	 * @return type
	 */	
	public static function updateTreeRoots($categories)
	{
		if(is_array($categories))
		{
			foreach($categories as $cat)
			{
				$node = Category::find($cat['id']);
				$node->parent_id = null;
				$node->save();
			}
		}
	}

	
	/**
	 * Rebuilds the tree: update descendants and their order
	 * @param type $categories 
	 * @return type
	 */
	public static function rebuildTree($categories)
	{
		if(is_array($categories))
		{
			
			foreach($categories as $cat)
			{
				$node = Category::find($cat['id']);
				
				//loop recursively through the children
				if(isset($cat['children']) && is_array($cat['children']))
				{
					foreach($cat['children'] as $child)
					{
						//append the children to their (old/new)parents
						$descendant = Category::find($child['id']);
						$node->append($descendant);

						//ordering trick here
                                               //shift the descendants to the bottom to get the right order at the end
						$shift = count($descendant->getSiblings());
						$descendant->down($shift);

						Category::rebuildTree($cat['children']);
					}
				}
			}
		}
	}
```

and That's it. I faced another problem in displaying as a tree, the database was fine, but the tree rendering was wrong. So i added another method in my model getChildren() instead of just doing $category->children, because i wanted them to be ordered by the _lft attribute.

```
	/**
	 * a method to get the children by order
	 * @param type $categories 
	 * @return type
	 */	
	public function getChildren()
	{
		return $this->children()->orderBy('_lft')->get();
	}
```

I did this quickly, maybe it is not the best way to do it, as i don't know how many calls i am doing to the db, (find() and save()) but for now, it fits my needs and time.

i pushed my changes, if you want to take a look, just follow the [Category Controller Sort() method](https://github.com/elieandraos/ddfc/blob/master/app/Http/Controllers/CategoryController.php)

hopefully i was helpful,

**Comment by DamjanZ** [comment]
@elieandraos thanks for help! Currently I am working on something else but I'll let you know in a hour how it works in my example. Regardless of performance, for my needs I think it should be enough. It's not that administrators will do reordering forum every day.
Btw, your picture link is broken.

**Comment by elieandraos** [comment]
@DamjanZ it is just a picture of a drag/drop tree 
yeah let me know if all went fine with you

**Comment by lazychaser** [comment]
You need only to record drag'n'drop operations and then post them to the server all at once rather than rebuilding the tree.

**Comment by DamjanZ** [comment]
@elieandraos I just tested your functions, had to do little tweaks (was testing with Postman) and works like charm! I'll see how will work from the front-end part.

**Comment by elieandraos** [comment]
@lazychaser that was the issue from the beginning me and @DamjanZ faced: how to post them to the server all at once. the array received from the post values is the correct order and tree structure, but i couldn't find a way to update the tree at once. any help ?

**Comment by lazychaser** [comment]
@elieandraos I told you already, you just record drag'n'drop operations (i.e. put this node before that node) and replay them on server

**Comment by elieandraos** [comment]
@lazychaser i got your point, i don't think the drag&drop scripts tells you though that this node has moved from this parent to another, it just generates the whole new tree structure (and personally i don't want to put an amount of time on front-end stuff to have this functionality), which is why the need of mass seeding sometimes (baum has it).

Your package is still great, keep up the good work and thanks for sharing it.

**Comment by lazychaser** [comment]
I believe that any package should have specific events, so you could record
actions =)

**Comment by lazychaser** [comment]
This now can be done effectively in `4.1.0@dev`. [Read the docs](https://github.com/lazychaser/laravel-nestedset#rebuilding-a-tree-from-array).

**Comment by Propaganistas** [comment]
Hi @lazychaser 
Great addition. Currently the `rebuildTree` method effectively maps parent-child relationships, but the order of siblings is lost.

Any chance to support this? You could go by just using the array order itself, or by checking for `lft` and `rgt` array keys...

**Comment by lazychaser** [comment]
The order is the same as it is specified in data array

**Comment by Propaganistas** [comment]
Oops I'm sorry, I made a mistake myself. Never mind!
