### ISSUE TITLE
linkNodes & toTree with where

### ISSUE THREAD

**Issue by chaotixlv** [lazychaser/laravel-nestedset#80]
Im building simple forum system for my project and using this code for forum index.
```
$forums = Forum::with(['last_post.topic.last_poster'])->get();
$forums->linkNodes();
$forums = $forums->toTree();
```
This makes 4 queries to get all data I need. But when it goes to specific forum with where statement linkNodes and toTree doesn't work here which makes alot more queries. Code:
```
$forum = Forum::where('key', $key)->with(['forums.last_post.topic.last_poster'])->firstOrFail();
$topics = ForumTopic::where('forum_id', $forum->id)->with(['user', 'last_poster'])->newest()->paginate(20);
```
This makes somewhere about 12-13 queries (I have few more queries here for various things). With linkNodes and toTree I would reduce query count to somewhere about 5-6. But unfornately it doesn't work on where or single row return.

It would be cool if there would be possibility to use linkNodes and toTree on single row responses.

**Comment by lazychaser** [comment]
I'm not sure what you want to achieve.

First of all, you don't need to call `linkNodes` with `toTree` because latter calls it implicitly.

Second, `toTree` just makes a tree from a list of nodes, what do you expect it to do with single node? Maybe you're trying to access `$form->parent->parent`? If so, you just need to select ancestors: `$ancestors = $forum->getAncestors();`. This will give you Eloquent collection and you can load relations like so: `$ancestors->load('last_post.topic.last_poster')`. If you're trying to access `$forum->children`, you need to preload them as you would normally do: `$forum->load('children.last_post.topic.last_poster');`.
